/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.MouseListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MandoInuzuka
 */
public class GUIInforme extends javax.swing.JFrame {

    /**
     * Creates new form GUIInforme
     */
    public GUIInforme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDesplazamiento = new javax.swing.JScrollPane();
        jtData = new javax.swing.JTable();
        jlReporte = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Carnet", "Nombre", "Edad"
            }
        ));
        jtData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDataMouseClicked(evt);
            }
        });
        barraDesplazamiento.setViewportView(jtData);

        jlReporte.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlReporte.setText("Reporte");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jlReporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAtras)
                    .addComponent(barraDesplazamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jlReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barraDesplazamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void jtDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDataMouseClicked
        //String salida="Carnet: "+jtData.getValueAt(jtData.getSelectedRow(),0)+"\nNombre: "+jtData.getValueAt(jtData.getSelectedRow(),1)+"\nEdad: "+jtData.getValueAt(jtData.getSelectedRow(),2)+"";
        // JOptionPane.showMessageDialog(null,salida);
    }//GEN-LAST:event_jtDataMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane barraDesplazamiento;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jlReporte;
    private javax.swing.JTable jtData;
    // End of variables declaration//GEN-END:variables

    public void setValores(String[][] datosFilas, String etiquetas[]) {
        if (datosFilas != null) {
            jtData.setModel(new DefaultTableModel(datosFilas, etiquetas));
            barraDesplazamiento.setViewportView(jtData);
        }
    }

    public void escucharTabla(MouseListener controlador) {
        jtData.addMouseListener(controlador);
    }
    

    public String[] getDatosFila() {

        String datos[] = new String[jtData.getColumnCount()];
        int filaSeleccionada = jtData.getSelectedRow();
        for (int columna = 0; columna < datos.length; columna++) {
            datos[columna] = jtData.getValueAt(filaSeleccionada, columna).toString().trim();
        }
        return datos;
    }


}
